title: blair's porfolio
name: Blair
email: cher.blair.h@gmail.com
description: >-
  the footsteps of a curious developer


baseurl: ""
url: "https://cherblair.github.io/portfolio.github.io/"


# profile 이미지
profile_image: images/me.jpg


# SNS 아이디
# facebook_id: babycheetah
# instagram_id: babycheetah


# Youtube vid
youtube_vid: #


# Custom Color
primary: 18568e
primary_hover: D3E5F5 #1fa69b
color_1: 2c98f0 
color_2: ec5453
color_3: f9bf3f
color_4: 095e21
color_5: 00132C #062F4F
color_6: FC6472 #2c98f0 
color_7: B8EDCF #ec5453
color_8: EFACA3 #f9bf3f
color_9: C3ECF0 #095e21
color_10: ECCEB2 #2fa499
color_11: A7F2EB #D9D2E9
color_12: D4BA7D #00132C
color_13: 90C9C0 #D9EAD3
color_14: D9D4B6 #2eb3bf
color_15: 24CCB5 #fce5cd
color_16: FAA818 #674ea7 
color_17: 41A30D #b45f06
color_18: FFCE38 #6fa8dc 
color_19: 367D7D #c2d431 
color_20: D33502 #9e296b 
color_21: 6EBCBC #b2c5c4 
color_22: 37526D #f2caca
color_23: ACCECD #6793bd 
color_24: B7AE9D #f1c232
color_25: 8A151B #c6d738


# slider type 0  (텍스트가 우측 정렬된 슬라이더)
slider_0: # 형식에 맞추어 항목 추가
- background_url: images/Matterhorn.jpg
  title: 😎
  subtitle: >- 
    JAVA <br>
    Spring / JPA <br>
    MariaDB / MySQL <br>
    JS / css / html
  position: absolute
  transform: translate( -50%, -50%)
  left: 140px
  bottom: 250px


# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/slide_b02.png
  title: Java <br> Backend+ <br> Developer
  subtitle: >- 
    The footsteps of a<br>
    STEADELY growing developer<br>
  position: absolute
  transform: translate( -50%, -50%)
  left: 140px
  bottom: 0px

# The secret of getting ahead is getting started.
# JAVA <br>
# Spring / JPA <br>
# MariaDB / MySQL <br>
# JS / css / html
# slider type 3  (텍스트가 좌측 정렬된 슬라이더)
slider_2: # 형식에 맞추어 항목 추가
- background_url: images/Matterhorn.jpg
  title: 
  subtitle: >- 
    
    
  position: absolute
  transform: translate( -50%, -50%)
  left: 140px
  bottom: 250px    


# About
about_meta: About Me
about_header: >- 
  "The secret of getting ahead is getting started."
about_introduce: >-
  "새로운 도전을 즐기는, 호기심 많은 개발자 🧐"
about_content: >-
 안녕하세요. <strong>3년동안 업무 전반을 달려온 Java 개발자 김하나(Blair)</strong> 입니다.<br><br>

 ✅ <strong> 도전과 성취가 있는 삶을 지향합니다. </strong><br>
 　 경영학을 전공한 저에게, 개발자로의 진로는 또 다른 세계로의 여행이었습니다.
  <strong>Java와 Android</strong>를 배워 개발자의 세상에 첫 발을 내딛었고, 이후 <strong>서버 개발과 프론트 작업, 기획, Flutter를 활용한 어플리케이션 개발</strong> 등 새로운 미션을 수행하며 성장해왔습니다.
  이론과 실무를 함께하며 시너지를 높이기 위해 업무와 병행하여 <strong>컴퓨터 과학과에 편입/졸업</strong> 하였으며 <strong>정보처리기사 자격증</strong>을 취득하였습니다.<br><br>

 ✅ <strong> 호기심이 많고 행동 지향적 입니다. </strong><br>
 　 이전 회사는 주차 솔루션을 가지고 있었습니다. 언젠가 마트 POS기에서 차량 할인 등록 시 반복적으로 주차 할인권이 적용되지 않는다는 문의가 들어왔습니다. 
  로컬 환경에서는 문제의 원인을 진단할 수 없었고, 결국 <strong>직접 현장을 찾아 테스트를 진행</strong>하며 대표님과 함께 문제의 원인을 찾아 그 자리에서 문제를 해결하였습니다. 
  그 과정에서 <strong>현장의 담당자와 소통</strong>하였고, 반복되는 문제에 대한 불만을 잠재울 수 있었습니다. 또한 이를 계기로 동일 마트 체인점에 설치된 프로그램을 모두 업데이트 하여 <strong>재발을 방지</strong>하였습니다.
  왜? 머릿 속에 물음표가 떠오르면 <strong>직접 몸으로 부딪혀 궁금증을 해결</strong>해왔고, 이러한 호기심이 동력이 되어 한층 더 성장할 수 있었습니다.<br><br>

 ✅ <strong> 지속적으로 나아갑니다. </strong><br>
 　 🔹꾸준히 <strong>학습</strong>합니다. 인프런과 패스트캠퍼스를 통해 Spring과 Jpa, Java, Algorithm을 틈틈히 학습하고 있습니다. <br>
 　 🔹온라인에서 만난 사람들과 함께 <strong>알고리즘 스터디</strong>를 진행하며 주 3회 문제를 풀고 있습니다. <br> 
 　 🔹<strong>영어 회화</strong> 어플리케이션을 통해 주 2회 꾸준히 학습하고 있습니다. <br>
 　 🔹<strong>체력을 단련</strong>합니다. 달리기와 테니스, 수영을 즐깁니다. <br>
 　 🔹집 근처 도서관에서 <strong>다양한 장르의 책</strong>을 빌려 읽습니다. <br><br><br>


about_services: # 형식에 맞추어 항목 추가, css > icomoon.css 파일 참고
- icon: icon-code
  name: Java
- icon: icon-data
  name: Server
- icon: icon-monitor
  name: Web
- icon: icon-phone3
  name: App

about_box_content: 
  "MOTIVATING EACH OTHER 🙌"

about_box_content_color: rgb(255, 255, 255) 

about_box_sub_content: >-
 개발자로 성장한 지난 3년 간 분위기 좋고 능력이 출중한 분들이 모인 작은 회사에서 개발자 커리어의 첫 발을 들여 
 운이 좋게도 <strong>백엔드에서 프론트엔드, 웹에서 앱, 사이트 기획부터 개발 QA, 유지보수 등 전반적인 업무 일선</strong>에서 다양한 일들을 체득하였습니다. 
 이후 저의 첫 둥지는 <strong>카카오 모빌리티의 자회사</strong>가 되어 더 큰 품에서 다양한 사람들과 협업을 할 수 있었습니다. <br><br>

 - [BE] <strong>Java와 Spring, JPA</strong>로 백엔드 실무를 다짐 <br>
 - [FE] <strong>Javascript와 html, css, Ajax, JQuery</strong>를 활용하여 반응형 웹 프론드엔드 작업 <br>
 - [기획] 채팅 앱, 아파트 주차 예약 앱 기획, 기존 운영 사이트에 추가되는 새로운 기능 기획 <br>
 - [QA] 업데이트 전 테스트 사항을 문서화하여 체크 <br>
 - [DB] <strong>MySql / MariaDB</strong> <br>
 - [MIDDLE] <strong>Tomcat</strong> <br>
 - [APP] <strong>flutter</strong>를 사용하여 <strong>안드로이드와 iOS 채팅 앱 출시 및 유지 보수</strong> <br><br>

 프로젝트를 도맡아 신뢰를 바탕으로 현장의 소리부터 회사 내부의 이슈들까지 모두 모아 <strong>더 나은 프로그램을 만들어 나가는 데 일조하는 개발자</strong> 입니다.

about_box_button:
  link: #
  name: sample


# Tech  skill
tech_meta: TECH SKILLS
tech_header: 저는 현재 이것을 할 수 있습니다.
tech_content: 언어는 Java를 기반으로 하고 있고, 다양한 프레임워크를 활용할 수 있습니다. 
tech_list: # 형식에 맞추어 항목 추가
- name: Java
  color: color-6
  animation: fadeInLeft
  percent: 80
  mark: 80
  content: 자바 언어의 기본적인 문법에 대해 알고 있으며, 자료구조 및 알고리즘을 자바로 공부하였습니다.<br><br>
- name: Spring
  color: color-7
  animation: fadeInRight
  percent: 70
  mark: 70
  content: 스프링 프레임 워크를 활용하여 MVC 패턴으로 다양한 요청을 처리할 수 있습니다. Model, View, Controller, Service 로직을 서비스 전반에 걸쳐 작업해왔습니다. 꾸준히 Spring 프레임워크에 대한 공부를 하고 있습니다. <br><br>
- name: DB
  color: color-8
  animation: fadeInLeft
  percent: 70
  mark: 70
  content: 데이터를 모델링하고 테이블 설계 및 관계성 설정 등을 할 수 있습니다. 실무에서는 MariaDB를 사용하였습니다.<br><br>
- name: JPA
  color: color-9
  animation: fadeInRight
  percent: 70
  mark: 70
  content: 실무에서 반복적인 CRUD SQL을 JPA로 처리하였으며, Join, many To one의 관계 등을 다루어보았습니다.<br> JPA로 처리하지 못하는 복잡한 쿼리의 경우에는 native query를 사용하여 작업 하였습니다.<br><br>
- name: MySQL
  color: color-10
  animation: fadeInLeft
  percent: 60
  mark: 60
  content: 기본적인 CRUD query에 익숙하며 여러 테이블 조인을 통하여 필요한 데이터를 조회할 수 있습니다. <br><br>  
- name: AWS
  color: color-11
  animation: fadeInRight
  percent: 20
  mark: 20
  content: 학과에서 AWS 수업을 수강하였고 간단한 실습도 해보았습니다. 클라우드 서버의 기본적인 이론을 알고 있습니다. <br><br>
- name: HTML
  color: color-12
  animation: fadeInLeft
  percent: 80
  mark: 80
  content: 마크업 언어 문법을 이해하고 화면을 구성할 수 있습니다. 반복적인 부분의 경우 템플릿화 하여 코드의 유지/보수를 용이하게 작업해왔습니다. <br><br>
- name: JavaScript
  color: color-13
  animation: fadeInRight
  percent: 70
  mark: 70
  content: Ajax, JQuery 기타 라이브러리 등을 사용하여 동적인 화면을 구성할 수 있습니다. gitHub의 ExcelJs를 활용하여 스크립트단에서 엑셀 파일을 다운로드 하는 로직을 구현하였고 프로젝트 전반에 적용한 경험이 있습니다. <br><br>
- name: css
  color: color-14
  animation: fadeInLeft
  percent: 50
  mark: 50
  content: 간단한 css 작업을 할 수 있습니다. chrome의 dev tools를 사용하여 css를 예시적으로 적용한 뒤 디자인/프론트엔드 담당과 협의하여 디자인을 수정하곤 했습니다. <br><br>
- name: Flutter
  color: color-15
  animation: fadeInRight
  percent: 70
  mark: 70
  content: flutter를 사용하여 채팅 앱을 만든 후 안드로이드와 iOS에 런칭하였고, 유지/보수 한 경험이 있습니다. <br> 언어는 Dart를 사용하였고, 화면 구성부터 Apatch 서버 구축, 백엔드 로직 개발, 웹서버와의 연동 등 전반적인 작업을 도맡아 진행하였습니다. <br><br>
- name: Android
  color: color-16
  animation: fadeInLeft
  percent: 70
  mark: 70
  content: 안드로이드 & JAVA 앱 교육 과정을 수료하였고, 안드로이드 스튜디오에서 flutter & Dart를 활용하여 앱을 출시한 경험이 있습니다. <br><br>
- name: git
  color: color-17
  animation: fadeInRight
  percent: 70
  mark: 70
  content: git을 사용한 버전 관리에 익숙합니다.<br> 기본적인 명령어를 숙지하고 있으며 여러 프로젝트에서 git을 사용하였습니다. <br><br>
- name: gitLab, gitHub
  color: color-18
  animation: fadeInLeft
  percent: 80
  mark: 80
  content: 학원 프로젝트 및 개인 프로젝트의 경우 gitHub를 사용하고, 회사에서는 gitLab을 사용하였습니다. 둘 다 익숙합니다. <br><br>
- name: jira
  color: color-19
  animation: fadeInRight
  percent: 80
  mark: 80
  content: 프로젝트 일정 관리, 이슈 공유 등의 프로그램으로 jira를 사용하였고, 이슈를 분석하여 필요한 데이터를 뽑아낼 수 있습니다. <br><br>
- name: notion
  color: color-20
  animation: fadeInLeft
  percent: 80
  mark: 80
  content: 회사의 공유 자료를 notion으로 만들어 직원들에게 공유한 적이 있으며, notion을 일상에서도 활용하고 있습니다. <br><br>
- name: slack
  color: color-21
  animation: fadeInRight
  percent: 80
  mark: 80
  content: 업무 협업 툴로 slack을 사용하여 익숙합니다. <br><br>



  
tech_desc: 강점은 더 강화하고 부족한 부분은 채우기 위해 직접 부딪혀보며 성장하고 있습니다. <strong>JAVA, Spring, JPA, AWS, docker, React, nodeJS, algorithm</strong>등을 계속해서 학습할 계획입니다. 


# Project
project_meta: My Work
project_header: PROJECT
# project_introduce: <span></span>
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)    # 더보기 내용
project_load_more_url: #

project_my_name: COMPANY PROJECT

project_my: # 형식에 맞추어 항목 추가
- background_url: images/pr_rs.png
  animation: fadeInLeft
  name: RS 이기종 통합 주차관제 솔루션
  description: 각기 다른 주차 장비를 연동하여 통합 제어 할 수 있는 프로그램 솔루션의 개발 및 유지 보수 <br> 2020.07 ~ 2023.05
  # detail_url: #
  readmore_url: pdf/rs-parking.pdf

- background_url: images/pr_illo.png
  animation: fadeInLeft
  name: 아파트 방문예약 앱
  description: 아파트 방문예약 앱 기획 및 데이터 모델링 <br> 2022.02 ~ 2022.03 
  # detail_url: #
  readmore_url: pdf/illo.pdf

- background_url: images/pr_chat.png
  animation: fadeInLeft
  name: SaidaTalk
  description: flutter로 Android와 iOS 채팅앱 기획 및 개발, 유지 보수 <br> 2021.08 ~ 2022.08
  # detail_url: #
  readmore_url: pdf/saida-talk.pdf

- background_url: images/pr_hahapet.png
  animation: fadeInLeft
  name: HAHAPET
  description: 반려동물 용품 판매 사이트 기획 및 개발, 유지 보수 <br> 2020.10 ~ 2022.08
  # detail_url: #
  readmore_url: pdf/hahapet.pdf

- background_url: images/pr_cb01.png
  animation: fadeInLeft
  name: C-bridge SAIDA
  description: K-CULTURE 글로벌 소통 플랫폼. <br> 추가 기능 개발 및 사이트 유지 보수 <br> 2020.10 ~ 2022.08
  # detail_url: #
  readmore_url: pdf/bridge.pdf

- background_url: images/pr_live.png
  animation: fadeInLeft
  name: c-bridge SAIDA On-live
  description: 생방송 실시간 송출 서비스. <br> 라이브 스트리밍 구현 보조, 기능 추가 및 유지 보수 <br> 2020.07 ~ 2020.12 
  # detail_url: #
  readmore_url: pdf/live.pdf
 

project_team_name: ACADEMY PROJECT
project_team: # 형식에 맞추어 항목 추가
- background_url: images/pr_pms.png
  animation: fadeInRight
  name: PMS system
  description: 팀원들과 함께 Spring 프레임워크를 활용하여 MVC 패턴에 기반한 PMS system 구축 <br> 2020.05 ~ 2020.06
  youtube_url: https://youtu.be/DJv8By_KxEM
  all_part_url: pdf/PMS_all_part.pdf
  my_part_url: pdf/PMS_mypart.pdf
  

- background_url: images/pr_kid.png
  animation: fadeInRight
  name: 어린이 체험 학습 사이트
  description: html, javascript, css, Oracle DB를 사용한 동적 화면 구현 <br> 2020.04
  youtube_url: https://youtu.be/wyUvBt7Xho0
  # detail_url: #

# project_business_name: Business
# project_business: # 형식에 맞추어 항목 추가
# - background_url: images/my_business.PNG
#   animation: fadeInTop
#   name: 인프런강의(2021~)
#   description: >-
#     취준과 대학원진학을 동시에 했을때 많은 곳에서 github 주소뿐만아니라 개발 블로그주소도 요청하는데가 많았다.(물론 필수는 아니였지만) 
#     또한 교육기관(멋쟁이사자처럼,네이버 부스트 캠프, 소마등)에서도 마찬가지이다. 현재 프로그래밍의 중요도가 올라가고있으며 초등학생부터 의무교육을 시작한다고 한다. 
#     많은 비전공자들이 뒤늦게 프로그래밍을 시작하고 있다. 열심히 배우고 지원할려니 개발 블로그를 요청한다... 프로그래밍을 시작할때 알았다면 얼마나 좋았을까. 
#     공부하면서 블로그 내용을 채웠으면 참 좋았을것이다. 이런 흐름을 캐치하여 나는 개발자다운 블로그인 깃헙블로그를 만드는 짧은 강의를 만들었다. 
#   detail_url: #
#   readmore_url: #


# Experience
exp_meta: What have I achieved?
exp_header: 저는 이런 "경험"들을 해봤습니다.
# exp_content: 
exp_services: # 형식에 맞추어 항목 추가
- name: 협업
  color: color-1
  icon: icon-share3
  content: 기획, FE, BE, QA, CS 등의 다양한 포지션을 모두 경험해보며 서로에 대한 이해를 높였습니다. <br> 팀원들 뿐 아니라 타 부서와의 협업에도 익숙합니다.
- name: 연구/개발
  color: color-2
  icon: icon-bulb
  content: 모든 프로젝트를 진행하면서 클라이언트의 요구사항을 대면하여 직접 듣고 발전 방향을 모색하였으며, 우선 순위를 선별하여 프로젝트를 개선해왔습니다.
- name: 기술습득
  color: color-3
  icon: icon-pencil #icon-home, icon-power, icon-flag power2 book2
  content: Java 개발자로 시작하여 FE, 앱 제작 등 그때 그때 필요한 기술을 배우고 실전에 적용하여 결과물을 만들어왔습니다.
- name: 프로젝트
  color: color-4
  icon:  icon-phone3
  content: 다양한 프로젝트를 기획, 진행 해왔기에 업무에 대한 흐름에 익숙합니다. 새로운 프로젝트에 도전적입니다.

exp_counters_bg_img: images/cat_bg.jpg
exp_counters:
# - name: Online Class Sales
#   count: 344
#   speed: 10000
- name: project
  count: 8
  speed: 5000


# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: 우아한 테크코스
  date: 2023.10 ~
  content: 우아한 형제들에서 주관하는 실전형 프로그래밍 과제 수행
  color: color-13
  icon: icon-server
  animation: fadeInRight
- name: RS SOLUTIONS
  date: 2020.07 ~ 2023.05
  content: 이기종 주차 시스템 연동 프로젝트 및 다양한 SI 프로젝트 수행
  color: color-1
  icon: icon-monitor
  animation: fadeInRight
- name: 정보처리기사 
  date: 2021.11
  content: 정보처리기사 자격증 취득
  color: color-3
  icon: icon-pen2
  animation: fadeInRight
- name: EZEN ACADEMY
  date: 2019.12 ~ 2020.06
  content: Java, Android Web & App 개발자 과정 수료
  color: color-4
  icon: icon-book2
  animation: fadeInRight


# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: KOREA NATIONAL OPEN UNIVERSITY
  subtitle: 한국방송통신대학교 <br> <strong>컴퓨터과학과 졸업</strong>
  date: 2021.03 - 2023.02
  content: >
   <strong>컴퓨터에 대한 이해도를 높이고 프로그래밍을 하는 데 필요한 지식의 기반을 다지기 위해</strong> 컴퓨터과학과에 편입하였습니다. <br>
   일과 학업을 병행하는 것이 쉽지는 않았지만, 출/퇴근 시간 및 짜투리 시간, 주말을 활용하여 <strong>두마리 토끼를 놓치지 않았습니다.</strong> <br>
   프로그래밍 언어론, c와 c++, Java, 데이터베이스 시스템, 모바일앱프로그래밍, 클라우드컴퓨팅(AWS) 등을 수강하며 다양한 이론을 배우고 실습을 진행했던 것이 다방면으로 많은 도움이 되었습니다. <br>
   이론을 배운 것이 <strong>정보처리기사</strong> 자격증을 취득 하는 데에도 플러스 요인이 되어 <strong>재학중에 자격증을 취득</strong>할 수 있었습니다. <br> 
   또한 정보통신공사업에 등록된 회사의 입장에서도 저의 전공과 정보처리기사 자격증이 정부사업을 따 오는 데에 도움이 되어 <strong>대표님과 상무님이 자격증의 취득을 많이 축하해주셨는데 저의 밤을 지새운 작은 노력이 회사에 기여</strong>를 한 것 같아 정말 뿌듯했었습니다.
- title: KANGWON NATIONAL UNIVERSITY
  subtitle: 강원대학교 <br> <strong>경영학과 졸업</strong>
  date: 2008.03 - 2012.02
  content: > 
   <strong>경영학을 전공</strong>하였으며, 팀프로젝트를 <strong>다수 수행하였고 팀장</strong>의 역할을 주로 맡아왔습니다. <br> 
   타 학과 수업도 많이 들었는데 영어영문학과에서 기말 과제로 팀원들과 <strong>영어 연극을 하고 좋은 성적을 거뒀던 것</strong>이 제일 기억에 남습니다. <br> 
   SIFE KOREA(현 Enactus KOREA)라는 글로벌 비즈니스 리더십 동아리 활동도 활발하게 참여했으며, 
   2011년에는 <strong>지역 어린이들에게 경제에 대한 개념을 가르치고 직접 플리마켓을 열어 수익을 창출한 프로젝트</strong>의 팀장 자격으로 발표자에 선정되어 학교 대표로 SIFE 국내 대회(NATIONAL COMPETITION)에 나가 <strong>준결승전에 진출</strong>한 경험이 있습니다.
- title: UIJEONGBU GIRLS HIGH SCHOOL
  subtitle: 의정부 여자 고등학교
  date: 2005.03 - 2008.02
  content: >
   <strong>RCY(Red Cross Youth)</strong>에 가입하여 동아리 활동을 하며 선후배들과 두루 어울렸습니다. <br>
   성격이 활발하여 반에서는 <strong>체육 부장</strong>을 맡아왔습니다. <br>
   학업과 체력 훈련을 병행하며 <strong>육군사관학교 진학</strong>을 꿈꾸었고, 시험 전 날 자율학습을 하던 친구들이 시험 잘 보고 오라며 초콜릿과 편지를 써주었던 것이 많이 기억에 남습니다. <br>
   <strong>호기심이 많아</strong> 수업이 끝나고도 선생님을 찾아 질문을 하던 학생이었고, 사회/문화 선생님과 한국지리 선생님께서 이런 학구열을 많이 응원해주셨습니다. <br>
   야간자율학습을 하며 대부분의 시간을 친구들과 함께했고, 많은 추억을 쌓았습니다. <br>
   고등학교 2학년 체육대회 때 영화 300의 스파르타 용사들이 되어 전력을 다해 <strong>줄다리기와 계주</strong>에서 승리했던 추억이 가장 즐거웠던 기억입니다.
   




# Blog
blog_meta: self-improvement
blog_header: GITHUB AND BLOG
blog_load_more: 더 발전하기 위해 항상 노력합니다    # 더보기 내용
# blog_load_more_url: #
blog_list:
- title: 
  subtitle: 
  date: 2023 ~
  content: 🐯 [Github] 온라인 스터디 및 공부 내용 정리
  thumbnail_url: images/github.png  #images/loader0.gif
  link: https://github.com/cherBlair
- title: 
  subtitle: 
  date: 2023 ~
  content: 📚 [Blog] 필요할 때 찾아보는 사전과 같은 블로그
  thumbnail_url: images/velog_1.png  #images/loader0.gif
  link: https://velog.io/@cher_blair

# - title: 
#   subtitle: 개발 블로그 운영
#   date: 2021.01
#   content: 여러 분야의 프로그래머들을 보면서 부러워도 하고 좌절도 하였지만 포기하지않고 어느 한분야라도 '장인'이 되겠다는 마음으로 꾸준히 개발 블로그를 운영해오고 있습니다.
#   thumbnail_url: images/blog-1.PNG
#   link: #
# - title: 따라쟁이의 유튜브
#   subtitle: 개발,논문 유튜브 채널 운영
#   date: 2018.04
#   content: 유튜브 채널을 운영하며 배운 것들을 정리해서 영상을 촬영하고 있습니다. 개인적으로 복습을 한번 더 하는 장점이 있습니다.
#   thumbnail_url: images/blog-2.PNG
#   link: #


# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: cher.blair.h@gmail.com
  icon: icon-globe-outline
# - title: 대한민국
#   icon: icon-map
- title: +82 10 9810 1101
  icon: icon-phone
# - title: 웹 주소
#   icon: icon-layers2
#   url: https://google.com
contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다.


optional_front_matter:
  remove_originals:    true
